import java.util.Scanner;
import java.util.TreeSet;
public class Q1 {
    public static void main(String[] args) {
        
        LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        doubleSet.add(2.718);
        doubleSet.add(2.718);
        doubleSet.add(2.718);
        System.out.println("LinkedHashSet: " + doubleSet);
        LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);
        LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);LinkedHashSet<Double> doubleSet = new LinkedHashSet<>();
        doubleSet.add(3.14);
        doubleSet.add(2.718);
        doubleSet.add(1.618);
        System.out.println("LinkedHashSet: " + doubleSet);
    }}
        
